import { ELEMENT_TYPES, CONTROL_ELEMENT, buildTrackingUrl, type ElementSlug } from "@/lib/email-test/tokens";

const TINY = 'width="1" height="1" style="width:1px;height:1px;border:0;display:inline-block;"';

function markup(slug: ElementSlug, url: string): string {
  switch (slug) {
    case "img":
      return `<img src="${url}" alt="" ${TINY} />`;
    case "background":
      return `<div ${TINY} style="width:1px;height:1px;background-image:url('${url}');"></div>`;
    case "video-poster":
      return `<video ${TINY} poster="${url}" controls></video>`;
    case "video-src":
      return `<video ${TINY} controls><source src="${url}" type="video/mp4" /></video>`;
    case "audio-src":
      return `<audio controls src="${url}" style="width:1px;height:1px;"></audio>`;
    case "source-src":
      // <source> nested in its own <audio> parent, distinct from the video-src test above.
      return `<audio controls style="width:1px;height:1px;"><source src="${url}" type="audio/mpeg" /></audio>`;
    case "track-src":
      return `<video ${TINY} controls><track src="${url}" kind="subtitles" srclang="en" label="English" /></video>`;
    case "object-data":
      return `<object data="${url}" type="image/gif" ${TINY}></object>`;
    case "embed-src":
      return `<embed src="${url}" type="image/gif" ${TINY} />`;
    case "iframe-src":
      return `<iframe src="${url}" ${TINY} title="tracking test"></iframe>`;
    case "script-src":
      return `<script src="${url}"></script>`;
    case "link-href":
      return `<link rel="stylesheet" href="${url}" />`;
    case "input-image":
      return `<input type="image" src="${url}" alt="" ${TINY} />`;
    case "svg-image":
      return `<svg width="1" height="1" style="width:1px;height:1px;"><image href="${url}" xlink:href="${url}" width="1" height="1" /></svg>`;
    default:
      return "";
  }
}

/**
 * Builds the full HTML test email. `<link>` tags are placed in <head> (a
 * dedicated stylesheet request), everything else sits in a labeled list in
 * <body>, with the tracking element itself kept visually tiny rather than
 * hidden outright.
 */
export function buildTestEmailHtml(
  appUrl: string,
  publicTestId: string,
  elementTokens: Record<ElementSlug, string>
) {
  const headLinks: string[] = [];
  const bodyRows: string[] = [];

  ELEMENT_TYPES.forEach(({ slug, label }, index) => {
    const url = buildTrackingUrl(appUrl, publicTestId, slug, elementTokens[slug]);
    const el = markup(slug, url);

    if (slug === "link-href") {
      headLinks.push(el);
      bodyRows.push(
        `<tr><td style="padding:6px 0;font:13px monospace;color:#16233A;">Test ${index + 1} — ${label}</td><td style="padding:6px 0;font:12px monospace;color:#4A5568;">(loaded via &lt;head&gt;, see above)</td></tr>`
      );
      return;
    }

    bodyRows.push(
      `<tr><td style="padding:6px 0;font:13px monospace;color:#16233A;">Test ${index + 1} — ${label}</td><td style="padding:6px 0;">${el}</td></tr>`
    );
  });

  const controlIndex = ELEMENT_TYPES.length + 1;
  bodyRows.push(
    `<tr><td style="padding:6px 0;font:13px monospace;color:#16233A;">Test ${controlIndex} — ${CONTROL_ELEMENT.label}</td><td style="padding:6px 0;"><canvas width="1" height="1" style="width:1px;height:1px;"></canvas> <span style="font:11px monospace;color:#4A5568;">(no src — should always stay at 0)</span></td></tr>`
  );

  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>HTML Tracking Element Test</title>
  ${headLinks.join("\n  ")}
</head>
<body style="margin:0;padding:24px;background:#FAFAF7;font-family:Arial,sans-serif;color:#16233A;">
  <h1 style="font-size:16px;margin:0 0 4px;">HTML Tracking Element Test</h1>
  <p style="font-size:12px;color:#4A5568;margin:0 0 16px;">Test ID: ${publicTestId}</p>
  <table role="presentation" style="border-collapse:collapse;width:100%;max-width:480px;">
    ${bodyRows.join("\n    ")}
  </table>
  <p style="font-size:11px;color:#4A5568;margin-top:20px;">
    This is a diagnostic email generated by Outbox's tracking test module.
    It intentionally contains no JavaScript-based tracking — only static
    HTML resources, to observe which ones your mail client requests.
  </p>
</body>
</html>`;
}
